config/routes.rb
Rails.application.routes.draw do
  root :to => 'books#top'
  get 'books' => 'books#index', as: 'books'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    book = Book.new(book_params)
    if book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(book.id)
    else
      @books = Book.all
      @book = book
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      flash.now[:alert] = ''
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<div class="form">
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="field">
    <label for="book_title">Title</label><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <label for="book_body">Body</label><br>
    <%= f.text_area :body %>
  </div>
  <div class="action">
    <%= f.submit 'Update Book'%>
  </div>
<% end %>
</div>
<%= link_to 'Show', book_path, :style=>"color:#7f7f7f;" %>
<span>|</span>
<%= link_to 'Back', books_path, :style=>"color:#7f7f7f;" %>

app/views/books/index.html.erb
<body>
  <h1 class="books">Books</h1>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Body</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book_path(book.id),:style=>"color:#7f7f7f;" %></td>
        <td><%= link_to 'Edit', edit_book_path(book.id),:style=>"color:#7f7f7f;" %></td>
        <td><%= link_to 'Destroy', destroy_book_path(book.id),:style=>"color:#7f7f7f;", method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <h2>New book</h2>
    <%= form_with model:@book, url:"/books", local:true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="field">
      <label for="book_title">Title</label><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <label for="book_body">Body</label><br>
      <%= f.text_area :body %>
    </div>
    <div class="action">
    <%= f.submit 'Create Book'%>
    </div>
  <% end %>
</body>

app/views/books/show.html.erb
<body>
  <p id="notice">
    <%=  notice %>
  </p>
  <p>
    <strong>Title: </strong>
    <%= @book.title %>
  </p>
  <p>
    <strong>Body: </strong>
    <%= @book.body %>
  </p>
  <%= link_to 'Edit', edit_book_path(@book.id), :style=>"color:#7f7f7f;" %>
  <span>|</span>
  <%= link_to 'Back', books_path, :style=>"color:#7f7f7f;" %>
</body>

app/views/books/top.html.erb
<div class="body">
  <h1>ようこそ <span class="Bookers">Bookers</span> へ！</h1>
  <p class="intro">
    <span class="bookers">Bookers</span>
    では、さまざまな書籍に関するあなたの意見や
  </p>
  <p class="intro">
    印象を共有し交換することができます
  </p>
  <p class="intro">
  <%= link_to 'start', books_path, :style=>"color:#666;"%>
  </p>
</body>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="alert">
  <h2 class="alert_top"> <%= model.errors.count %> errors prohibited this book from being saved: </h3>
  <ul class="alert_item">
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>